name: Mirror to Codeberg

on:
  push:
    branches: [ main, master ]

jobs:
  codeberg_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Codeberg
        env:
          CB_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          # Push all branches and tags to Codeberg forcefully to keep them mirrored
          git push --prune --force https://${{ github.repository_owner }}:${CB_TOKEN}@codeberg.org/${{ github.repository_owner }}/${{ github.event.repository.name }}.git refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
